/*-----------------------------------------------------------------------------------------------------------
  $Archive: /SQL.root/SQL/Database/Build Local.sql $
  $Revision: 1 $
  $Date: 12/18/06 15:46 $
  $Author: mls $
  
  SQLCMD script for building the the Dreamdb database and initialize its state on DEP0358. 

-----------------------------------------------------------------------------------------------------------*/
:setvar server ZANZIBAR
:setvar dbname Dreamdb

-- Local VSS working folder (solution root)
:setvar solutions "C:\Solutions\Dreamdb\"
:setvar sqlroot "C:\Solutions\Dreamdb\SQL\"

-- Paths for data file and log file (filenames are generated by the Database.sql script)
:setvar mdfpath "C:\Data\User\"
:setvar ldfpath "C:\Data\User\"

-- Path for .NET sdk (must contain MSBuild and SQLServer.targets)
:setvar sdkpath C:\Windows\Microsoft.NET\Framework\v2.0.50727\

-- Initiate SQLCMD build scripts.
:r $(sqlroot)Database\"Create Database.sql"
:r $(sqlroot)Database\"Create Messages.sql"
:r $(sqlroot)Database\"Create Schemas.sql"
:r $(sqlroot)Database\"Create Tables.sql"
:r $(sqlroot)Database\"Create Views.sql"
:r $(sqlroot)Database\"Create Functions.sql"
:r $(sqlroot)Database\"Create Procedures.sql"
:r $(sqlroot)Database\"Create CLR Objects.sql"
go